{{- $adminPassword := randAlphaNum 32 -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "admin-console.labels" . | nindent 4 }}
  name: kotsadm-password
data:
  passwordBcrypt: {{ default $adminPassword .Values.adminConsole.password | bcrypt | b64enc }}
  passwordB64: {{ default $adminPassword .Values.adminConsole.password | b64enc }}