name: 'Start Production Release Workflow'
description: 'Start production release workflow'
inputs:
  gh_token:
    description: 'GitHub token'
    required: true
  ref:
    description: 'Full SHA of the commit to release (usually this will be the latest commit)'
    required: true
  run_id:
    description: 'Run ID of the workflow run that triggered this action'
    required: true
outputs:
  next_step:
    description: 'Next step action: "stop" or "release"'
runs:
  using: 'node20'
  main: 'index.js'
