name: images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v2.1.5
        with:
          go-version: '^1.19'

      - name: setup env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - uses: actions/checkout@v2.3.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1.14.1
        name: log in to docker registry
        with:
          registry: registry.staging.replicated.com
          username: service-account
          password: ${{ secrets.REPLICATED_TOKEN }}
          push: true

      - name: Build api image
        uses: docker/build-push-action@v2.10.0
        with:
          username: service-account
          password: ${{ secrets.REPLICATED_TOKEN }}
          context: .
          tags: registry.staging.replicated.com/dmitriy-kots/slackernews-api:tag123
          file: ./deploy/Dockerfile
          push: true
