on:
  push:
    branches:
      - main

name: "Staging testim"

jobs:
  wait-for-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: replicatedhq/action-wait-for@v1
        with:
          ref: ${{ github.sha }}
          timeout: 1800
          check-regexp: (deploy-staging.*|commit.*|build-and-test.*)

  testim-staging:
    needs:
      - wait-for-deploy
    steps:
      - id: release-staging
        run: |
          echo "release ${{ github.sha }}"
          sleep 10

  release-production:
    if: success()
    needs:
      - testim-staging
    steps:
      - id: release
        run: |
          echo "release ${{ github.sha }}"
