on:
  push:
    branches:
      - main

name: "Staging testim"

jobs:
  wait-for-deploy:
    runs-on: ubuntu-22.04
    steps:
      - id: wait-for-deploy
        run: |
          echo "wait for ${{ github.sha }}"
          sleep 1

  testim-staging:
    needs:
      - wait-for-deploy
    runs-on: ubuntu-22.04
    steps:
      - id: release-staging
        run: |
          echo "release ${{ github.sha }}"
          sleep 1

  # THIS
  get-previous-release-sha:
    needs:
      - testim-staging
    runs-on: ubuntu-22.04
    outputs:
      sha: ${{ steps.get-latest-release.outputs.sha }}
      tag_name: ${{ steps.get-latest-release.outputs.tag_name }}
    steps:
      - id: get-latest-release
        uses: actions/github-script@v6
        with:
          script: |
            const {
              data: { tag_name: previous_tag_name },
            } = await github.rest.repos.getLatestRelease({
              ...context.repo,
            });
            const {
              data: { object: { sha: old_sha } },
            } = await github.rest.git.getRef({
              ...context.repo,
              ref: `tags/${previous_tag_name}`,
            })
            core.setOutput("sha", old_sha);
            core.setOutput("tag_name", previous_tag_name);

  can-trigger-production-release:
    needs:
      - get-previous-release-sha
    runs-on: ubuntu-22.04
    outputs:
      block_release: ${{ steps.changed.outputs.diff }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: changed
        run: |
          if git diff --quiet ${{ needs.get-previous-release-sha.outputs.sha }}..${{ github.sha }} -- block_release; then
            echo "diff=false" >> "${GITHUB_OUTPUT}"
          else
            echo "diff=true" >> "${GITHUB_OUTPUT}"
          fi

  release-production:
    if: success() && needs.can-trigger-production-release.outputs.block_release == 'false'
    needs:
      - can-trigger-production-release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - id: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "release ${{ github.sha }}"
          gh workflow run release-production.yml -f ref=${{ github.sha }} --ref main
          echo "hi"

