on:
  push:
    branches:
      - main

name: "Staging testim"

jobs:
  wait-for-deploy:
    runs-on: ubuntu-22.04
    steps:
      - id: wait-for-deploy
        run: |
          echo "wait for ${{ github.sha }}"
          sleep 10

  testim-staging:
    needs:
      - wait-for-deploy
    runs-on: ubuntu-22.04
    steps:
      - id: release-staging
        run: |
          echo "release ${{ github.sha }}"
          sleep 10

  release-production:
    if: success()
    needs:
      - testim-staging
    runs-on: ubuntu-22.04
    steps:
      - id: release
        run: |
          echo "release ${{ github.sha }}"
          gh workflow run release-production.yml -f ref=${{ github.sha }} --ref main
